### Read API Info
# @name apiInfo
GET {{$dotenv cf_api}}/info
### Fill Variables from Response
@authorization_endpoint = {{apiInfo.response.body.authorization_endpoint}}
### Get Access Token
# @name requestAccessToken
POST {{authorization_endpoint}}/oauth/token?grant_type=password
Content-Type: application/x-www-form-urlencoded;charset=utf-8
Accept: application/json
Authorization: Basic Y2Y6

username={{$dotenv username}}
&password={{$dotenv password}}

### Fill Variables from Response
@bearerToken = {{requestAccessToken.response.body.access_token}}

### Read Application Registration Details
GET {{$dotenv saas_registry_url}}/saas-manager/v1/application
Authorization: {{bearerToken}}